version: '3'

services:
  app:
    build: book_management
    container_name: books-django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - db
      - redis
      - celery
  db:
    build: mysql
    container_name: books-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: books-redis
    ports:
      - "6379:6379"
  celery:
    build: book_management
    container_name: books-celery
    command: sh -c "celery --app=book_management worker --loglevel=info --pool=solo"
    env_file:
      - .env
    depends_on:
      - redis
